In [7]:
import pandas as pd

In [ ]:
nyc_payroll = pd.read_csv("../data/Citywide_Payroll_Data_(Fiscal_Year)_20260415.csv", low_memory=False)

In [9]:
nyc_payroll.columns

Index(['Fiscal Year', 'Payroll Number', 'Agency Name', 'Last Name',
       'First Name', 'Mid Init', 'Agency Start Date', 'Work Location Borough',
       'Title Description', 'Leave Status as of June 30', 'Base Salary',
       'Pay Basis', 'Regular Hours', 'Regular Gross Paid', 'OT Hours',
       'Total OT Paid', 'Total Other Pay'],
      dtype='str')

In [10]:
nyc_payroll.head()

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
0,2025,67.0,ADMIN FOR CHILDREN'S SVCS,BLANCO,ELMER,S,02/04/2013,MANHATTAN,PROGRAM EVALUATOR,ACTIVE,"$95,897.00",per Annum,"1,820","$89,097.13",0,$0.00,$699.41
1,2025,67.0,ADMIN FOR CHILDREN'S SVCS,OTERO,MATTHEW,P,02/22/2011,BRONX,CHILD PROTECTIVE SPECIALIST SUPERVISOR,ACTIVE,"$100,050.00",per Annum,"1,820","$96,959.10",73,"$4,291.75","$6,935.28"
2,2025,67.0,ADMIN FOR CHILDREN'S SVCS,PASCALL,DERRICK,F,02/22/2011,MANHATTAN,CHILD PROTECTIVE SPECIALIST SUPERVISOR,ACTIVE,"$106,346.00",per Annum,"1,820","$100,503.13",0,$0.00,$732.41
3,2025,67.0,ADMIN FOR CHILDREN'S SVCS,DAUCHER,MEGHAN,B,02/28/2011,MANHATTAN,AGENCY ATTORNEY,ACTIVE,"$127,802.00",per Annum,"1,820","$82,894.55",0,$0.00,"$9,804.97"
4,2025,67.0,ADMIN FOR CHILDREN'S SVCS,JENKINS,LAMAR,T,06/03/2024,BRONX,SPECIAL OFFICER,ACTIVE,"$39,206.00",per Annum,"2,080","$37,769.10",354.75,"$10,000.28","$7,737.53"

In [14]:
nyc_payroll_2025 = nyc_payroll[nyc_payroll['Fiscal Year'] == 2025]

In [16]:
nyc_payroll_2025_Active = nyc_payroll_2025[nyc_payroll_2025['Leave Status as of June 30'] == 'ACTIVE']

I use Ai for this code below, I don't know how to clean the "$" and "," in the money cell

In [21]:
nyc_payroll_2025_Active['Total OT Paid Clean'] = nyc_payroll_2025_Active['Total OT Paid'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)

In [22]:
agency_ot = (
    nyc_payroll_2025_Active
    .groupby('Agency Name')['Total OT Paid Clean']
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)
agency_ot

                      Agency Name  Total OT Paid Clean
0               POLICE DEPARTMENT         1.012940e+09
1                 FIRE DEPARTMENT         5.472941e+08
2        DEPARTMENT OF CORRECTION         3.473289e+08
3           NYC HOUSING AUTHORITY         1.970786e+08
4        DEPARTMENT OF SANITATION         1.968010e+08
5    DEPARTMENT OF TRANSPORTATION         1.006700e+08
6     HRA/DEPT OF SOCIAL SERVICES         7.218018e+07
7  DEPT OF ENVIRONMENT PROTECTION         5.952930e+07
8       ADMIN FOR CHILDREN'S SVCS         4.943636e+07
9   DEPARTMENT OF EDUCATION ADMIN         3.250196e+07

In [27]:
nypd = nyc_payroll_2025_Active[nyc_payroll_2025_Active['Agency Name'] == 'POLICE DEPARTMENT']

In [30]:
nypd_title = (
    nypd.groupby('Title Description')['Total OT Paid Clean']
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)
nypd_title

                         Title Description  Total OT Paid Clean
0                           POLICE OFFICER         4.351856e+08
1                          P.O. DA DET GR3         1.336840e+08
2                                SERGEANT-         1.014796e+08
3                      SCHOOL SAFETY AGENT         5.369245e+07
4                               LIEUTENANT         5.339854e+07
5      POLICE OFFICER D/A DETECTIVE 2ND GR         4.131882e+07
6                            P.O. DET SPEC         3.902133e+07
7                TRAFFIC ENFORCEMENT AGENT         2.869582e+07
8  SERGEANT-D/A SUPERVISOR DETECTIVE SQUAD         1.886796e+07
9      POLICE OFFICER D/A DETECTIVE 1ST GR         1.834192e+07